src/Entity/Run.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RunRepository")
 * @ApiResource(normalizationContext={"groups"={"run"}})
 */
class Run
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Cluster", inversedBy="runs")
     * @ORM\JoinColumn(nullable=false)
     * @Groups({"run"})
     */
    private $cluster;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Program", inversedBy="runs")
     * @ORM\JoinColumn(nullable=true)
     * @Groups({"run"})
     */
    private $program;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"run"})
     */
    private $start;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"run"})
     */
    private $label;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups({"run"})
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"run"})
     */
    private $dateend;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"run"})
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RunStep", mappedBy="run", cascade={"remove"})
     * @Groups({"run"})
     */
    private $steps;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"run"})
     */
    private $uuid;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"run"})
     */
    private $timestamp;

    public function __construct()
    {
        $this->steps = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCluster(): ?Cluster
    {
        return $this->cluster;
    }

    public function setCluster(?Cluster $cluster): self
    {
        $this->cluster = $cluster;

        return $this;
    }

    public function getProgram(): ?Program
    {
        return $this->program;
    }

    public function setProgram(?Program $program): self
    {
        $this->program = $program;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(?\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(?string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->dateend;
    }

    public function setDateEnd(?\DateTimeInterface $dateend): self
    {
        $this->dateend = $dateend;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|RunStep[]
     */
    public function getSteps(): Collection
    {
        return $this->steps;
    }

    public function addStep(RunStep $step): self
    {
        if (!$this->steps->contains($step)) {
            $this->steps[] = $step;
            $step->setRun($this);
        }

        return $this;
    }

    public function removeStep(RunStep $step): self
    {
        if ($this->steps->contains($step)) {
            $this->steps->removeElement($step);
            // set the owning side to null (unless already changed)
            if ($step->getRun() === $this) {
                $step->setRun(null);
            }
        }

        return $this;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(?string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getTimestamp(): ?int
    {
        return $this->timestamp;
    }

    public function setTimestamp(?int $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }

}

templates/control/new-play.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block panelTitle %}
<h1 class="h2">New Play</h1>
{% endblock %}

{% block panelContent %}
    <div class="m-auto pt-5">
    {% form_theme form 
      'bootstrap_4_layout.html.twig' %}
    {{ form_start(form) }}
    {{ form_widget(form.recipe) }}
    <div class="m-3">
    <button class="btn btn-light">{{ button_label|default('Play') }}</button>
    <a class="btn btn-light" href="{{ path('home') }}">Cancel</a>
    </div>
    {{ form_end(form) }}
    </div>
{% endblock %}

templates/control/new-run.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block panelTitle %}
<h1 class="h2 text-light">New Run</h1>
{% endblock %}

{% block panelContent %}
  
 	{% 
 		form_theme form 
 			'bootstrap_4_layout.html.twig'
 			'jquery.collection.html.twig'
 			 %}
    {{ form_start(form) }}
    <div class="row">
        <div class="col">
            {% if edit is defined %}
                {{ form_row(form.label, {'label_attr': { class: 'text-light'}}) }}
            {% else %}
                {{ form_row(form.label, {'value' : "run_" ~ "now"|date("Y-m-d_H:i:s"), 'label_attr': { class: 'text-light'}}) }}
            {% endif %}
        </div>
        <div class="col">
            {{ form_row(form.program, {'label_attr': { class: 'text-light'}}) }}
        </div>
    </div>
    {{ form_widget(form.description, {'attr': { "class": "d-none d-lg-block"}}) }}
    <div class="row">
    	<div class="col">
    		{{ form_row(form.start, {'label_attr': { class: 'text-light'}}) }}
    	</div>
    </div>
    {{ form_widget(form) }}
    <button class="btn btn-light">{{ button_label|default('Save')|trans }}</button>
    <a class="btn btn-light" href="{{ path('run') }}">{% trans %}Cancel{% endtrans %}</a>
    {{ form_end(form) }}


{% endblock %}

templates/control/runs.html.twig
{% extends 'base.html.twig' %}

{% block panelContent %}

{% for message in app.flashes('info') %}
	<div class="alert alert-success" role="alert">
        {{ message }}
    </div>
{% endfor %}

<ul class="nav nav-tabs" id="myTab" role="tablist">
	<li class="nav-item">
		<a class="nav-link active" id="running-tab" data-toggle="tab" href="#running" role="tab" aria-controls="running" aria-selected="true">{% trans %}Running{% endtrans %}</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" id="scheduled-tab" data-toggle="tab" href="#scheduled" role="tab" aria-controls="scheduled" aria-selected="false">{% trans %}Scheduled{% endtrans %}</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" id="past-tab" data-toggle="tab" href="#past" role="tab" aria-controls="past" aria-selected="false">{% trans %}Past{% endtrans %}</a>
	</li>
	<li class="nav-item">
		<a class="nav-link" id="new-tab" data-toggle="tab" href="#new" role="tab" aria-controls="new" aria-selected="false">{% trans %}New{% endtrans %}</a>
	</li>
</ul>

<div class="tab-content" id="myTabContent">
	<div class="tab-pane fade show active" id="running" role="tabpanel" aria-labelledby="running-tab">
		<div class="row pt-3">
			<div class="col">
				<ul class="list-group list-group-flush">
				{% for run in running_runs %}
					<li class="list-group-item d-flex justify-content-between">
						<span>{{ run.label }} // Cluster #{{ run.cluster.label }}</span>
						<span>{{ run.start|date("Y-m-d H:i:s") }}</span>
						<div class="d-inline">
							<button class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#run-detail-{{ run.id }}">
					        	<span data-feather="help-circle"></span>
					        </button>
					        <button class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#modal-delete-run-{{ run.id }}">
					        	<span data-feather="trash-2"></span>
					        </button>
					     
						</div>
					</li>
					<div class="modal fade" id="modal-delete-run-{{ run.id }}">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-footer">
									<button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal" aria-label="Close">
										Cancel
									</button>
									<a class="btn btn-sm btn-outline-danger" href="{{ path('delete-run', { 'id': run.id }) }}">
										<span data-feather="trash-2"> Confirm delete</span>
							        </a>
								</div>
							</div><!-- /.modal-content -->
						</div><!-- /.modal-dialog -->
					</div><!-- /.modal -->
					<div class="modal fade" id="run-detail-{{ run.id }}">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h4 class="modal-title">Run #{{ run.id }}</h4>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<p class="text-muted my-1 border-bottom">{{ run.label }}</p>
									<p>Start: {{ run.start|date("Y-m-d H:i:s") }}</p>
									<p>End: {{ run.dateEnd|date("Y-m-d H:i:s") }}</p>
									<p>Cluster: {{ run.cluster.label }}</p>
								</div>
								<div class="modal-footer">
									<a class="btn btn-sm btn-outline-secondary" href="{{ path('edit-run', { 'id': run.id }) }}">
										<span data-feather="edit"> Edit</span>
					        		</a>
								</div>
							</div><!-- /.modal-content -->
						</div><!-- /.modal-dialog -->
					</div><!-- /.modal -->
				{% endfor %}
				</ul>
			</div>
		</div>
	</div>
	<div class="tab-pane fade" id="scheduled" role="tabpanel" aria-labelledby="scheduled-tab">
		<div class="row pt-3">
			<div class="col">
				<ul class="list-group list-group-flush">
				{% for run in coming_runs %}
					<li class="list-group-item d-flex justify-content-between">
						<span>{{ run.label }} // Cluster #{{ run.cluster.label }}</span>
						<span>{{ run.start|date("Y-m-d H:i:s") }}</span>
						<div class="d-inline">
							<button class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#run-detail-{{ run.id }}">
					        	<span data-feather="help-circle"></span>
					        </button>
					        <button class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#modal-delete-run-{{ run.id }}">
					        	<span data-feather="trash-2"></span>
					        </button>
					     
						</div>
					</li>
					<div class="modal fade" id="modal-delete-run-{{ run.id }}">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-footer">
									<button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal" aria-label="Close">
										Cancel
									</button>
									<a class="btn btn-sm btn-outline-danger" href="{{ path('delete-run', { 'id': run.id }) }}">
										<span data-feather="trash-2"> Confirm delete</span>
							        </a>
								</div>
							</div><!-- /.modal-content -->
						</div><!-- /.modal-dialog -->
					</div><!-- /.modal -->
					<div class="modal fade" id="run-detail-{{ run.id }}">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h4 class="modal-title">Run #{{ run.id }}</h4>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<p class="text-muted my-1 border-bottom">{{ run.label }}</p>
									<p>Start: {{ run.start|date("Y-m-d H:i:s") }}</p>
									<p>End: {{ run.dateEnd|date("Y-m-d H:i:s") }}</p>
									<p>Cluster: {{ run.cluster.label }}</p>
								</div>
								<div class="modal-footer">
									<a class="btn btn-sm btn-outline-secondary" href="{{ path('edit-run', { 'id': run.id }) }}">
										<span data-feather="edit"> Edit</span>
					        		</a>
								</div>
							</div><!-- /.modal-content -->
						</div><!-- /.modal-dialog -->
					</div><!-- /.modal -->
				{% endfor %}
				</ul>
			</div>
		</div>
	</div>
	<div class="tab-pane fade" id="past" role="tabpanel" aria-labelledby="past-tab">
		<div class="row pt-3">
			<div class="col">
				<ul class="list-group list-group-flush">
				{% for run in past_runs %}
					<li class="list-group-item d-flex justify-content-between">
						<span>{{ run.label }} // Cluster #{{ run.cluster.label }}</span>
						<span>{{ run.start|date("Y-m-d H:i:s") }}</span>
						<div class="d-inline">
							<button class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#run-detail-{{ run.id }}">
					        	<span data-feather="help-circle"></span>
					        </button>
					        <button class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#modal-delete-run-{{ run.id }}">
					        	<span data-feather="trash-2"></span>
					        </button>
					     
						</div>
					</li>
					<div class="modal fade" id="modal-delete-run-{{ run.id }}">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-footer">
									<button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal" aria-label="Close">
										Cancel
									</button>
									<a class="btn btn-sm btn-outline-danger" href="{{ path('delete-run', { 'id': run.id }) }}">
										<span data-feather="trash-2"> Confirm delete</span>
							        </a>
								</div>
							</div><!-- /.modal-content -->
						</div><!-- /.modal-dialog -->
					</div><!-- /.modal -->
					<div class="modal fade" id="run-detail-{{ run.id }}">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h4 class="modal-title">Run #{{ run.id }}</h4>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<p class="text-muted my-1 border-bottom">{{ run.label }}</p>
									<p>Start: {{ run.start|date("Y-m-d H:i:s") }}</p>
									<p>End: {{ run.dateEnd|date("Y-m-d H:i:s") }}</p>
									<p>Cluster: {{ run.cluster.label }}</p>
								</div>
								<div class="modal-footer">
									<a class="btn btn-sm btn-outline-secondary" href="{{ path('edit-run', { 'id': run.id }) }}">
										<span data-feather="edit"> Edit</span>
					        		</a>
								</div>
							</div><!-- /.modal-content -->
						</div><!-- /.modal-dialog -->
					</div><!-- /.modal -->
				{% endfor %}
				</ul>
			</div>
		</div>
	</div>
	<div class="tab-pane fade" id="new" role="tabpanel" aria-labelledby="new-tab">
		<div class="row pt-3">
			{% for cluster in clusters %}
				<div class="col-sm-8 col-md-6">
					<div class="card">
						<div class="card-body d-flex justify-content-between">
							<div class="card-text">{% trans %}Cluster{% endtrans %} #{{ cluster.label }}</div>
							<div class="d-inline">
								<div class="btn-group">
									<button class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#cluster-detail-{{ cluster.id }}">
							        	<span data-feather="help-circle"></span>
							        </button>
							        <a href="{{ path('new-run', {'id': cluster.id }) }}" class="btn btn-sm btn-outline-secondary"><span data-feather="plus-square"> </span> <span class="d-none d-lg-inline">{{ 'runs.button.new'|trans }}</span></a>
						        </div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal fade" id="cluster-detail-{{ cluster.id }}">
					<div class="modal-dialog" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h4 class="modal-title">{% trans %}Cluster{% endtrans %} #{{ cluster.label }}</h4>
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">
								<p class="text-muted my-1 border-bottom">{{ cluster.description }}</p>
								<ul class="list-group list-group-flush">
								{% for luminaire in cluster.luminaires %}
								    <li class="list-group-item d-flex justify-content-between align-items-center">Address: {{ luminaire.address }}; Row/Col: {{ luminaire.ligne }}/{{ luminaire.colonne }}</li>
								{% endfor %}
								</ul>
							</div>
						</div><!-- /.modal-content -->
					</div><!-- /.modal-dialog -->
				</div><!-- /.modal -->
			{% endfor %}
		</div>
	</div>
</div>




{% endblock %}

{% block bottomButton %}

{% endblock %}